# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atvalinajums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('something', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Lietotajs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vards', models.CharField(max_length=50)),
                ('uzvards', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='atvalinajums',
            name='lietotajs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylist.Lietotajs'),
        ),
    ]
