# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mylist', '0004_auto_20170420_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ieraksts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merkis', models.CharField(max_length=20)),
                ('datums_no', models.DateField(blank=True, null=True)),
                ('datums_lidz', models.DateField(blank=True, null=True)),
                ('vieta', models.CharField(blank=True, max_length=50, null=True)),
                ('statuss', models.BooleanField(default=False)),
                ('lietotajs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='atvalinajums',
            name='lietotajs',
        ),
        migrations.RemoveField(
            model_name='komandejums',
            name='lietotajs',
        ),
        migrations.DeleteModel(
            name='Atvalinajums',
        ),
        migrations.DeleteModel(
            name='Komandejums',
        ),
    ]
