# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0005_auto_20170515_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atvalinajums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iesniegums', models.FileField(upload_to=b'')),
                ('ieraksts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylist.Ieraksts')),
            ],
        ),
        migrations.CreateModel(
            name='Komandejums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atskaite', models.FileField(upload_to=b'')),
                ('ceks', models.FileField(upload_to=b'')),
                ('ieraksts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylist.Ieraksts')),
            ],
        ),
    ]
