# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0006_atvalinajums_komandejums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ieraksts',
            name='merkis',
            field=models.CharField(choices=[('komandejums', 'Komandejums'), ('atvalinajums', 'Atvalinajums')], max_length=20),
        ),
        migrations.AlterField(
            model_name='komandejums',
            name='ceks',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
