# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0008_saglabatielietotaji'),
    ]

    operations = [
        migrations.CreateModel(
            name='Norikojums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norikojums', models.FileField(upload_to=b'')),
                ('ieraksts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylist.Ieraksts')),
            ],
        ),
    ]
